# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\"\x07\n\x05\x45mpty\"%\n\x04Note\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\" \n\rSuccessStatus\x12\x0f\n\x07success\x18\x01 \x02(\x08\"9\n\x13\x41uthenticationToken\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x1c\n\x08Username\x12\x10\n\x08username\x18\x01 \x02(\t\")\n\tUsernames\x12\x1c\n\tusernames\x18\x01 \x03(\x0b\x32\t.Username\"\'\n\x13ListUsernamesParams\x12\x10\n\x08wildcard\x18\x01 \x02(\t\"M\n\nSendParams\x12\x19\n\x11receiver_username\x18\x01 \x02(\t\x12\x17\n\x0fsender_username\x18\x02 \x02(\t\x12\x0b\n\x03msg\x18\x03 \x02(\t\"R\n\x0b\x43hatMessage\x12\x19\n\x11receiver_username\x18\x01 \x02(\t\x12\x17\n\x0fsender_username\x18\x02 \x02(\t\x12\x0f\n\x07message\x18\x03 \x02(\t\"3\n\x16PendingMessagesPayload\x12\x19\n\x03msg\x18\x01 \x03(\x0b\x32\x0c.ChatMessage\"j\n\x13ReturnStatusPayload\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x11\n\tserverMsg\x18\x02 \x01(\t\x12/\n\x0esuccessPayload\x18\x03 \x01(\x0b\x32\x17.PendingMessagesPayload2\xdf\x03\n\nChatServer\x12\x35\n\x05Login\x12\x14.AuthenticationToken\x1a\x14.ReturnStatusPayload\"\x00\x12\x33\n\tCreateAct\x12\x14.AuthenticationToken\x1a\x0e.SuccessStatus\"\x00\x12(\n\tDeleteAct\x12\t.Username\x1a\x0e.SuccessStatus\"\x00\x12.\n\x06Status\x12\t.Username\x1a\x17.PendingMessagesPayload\"\x00\x12\x33\n\rListUsernames\x12\x14.ListUsernamesParams\x1a\n.Usernames\"\x00\x12.\n\x07SendMsg\x12\x0b.SendParams\x1a\x14.ReturnStatusPayload\"\x00\x12\x37\n\x0fListPendingMsgs\x12\t.Username\x1a\x17.PendingMessagesPayload\"\x00\x12%\n\x06Logout\x12\t.Username\x1a\x0e.SuccessStatus\"\x00\x12$\n\nChatStream\x12\x06.Empty\x1a\x0c.ChatMessage0\x01\x12 \n\x08SendNote\x12\x0c.ChatMessage\x1a\x06.Empty')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=14
  _EMPTY._serialized_end=21
  _NOTE._serialized_start=23
  _NOTE._serialized_end=60
  _SUCCESSSTATUS._serialized_start=62
  _SUCCESSSTATUS._serialized_end=94
  _AUTHENTICATIONTOKEN._serialized_start=96
  _AUTHENTICATIONTOKEN._serialized_end=153
  _USERNAME._serialized_start=155
  _USERNAME._serialized_end=183
  _USERNAMES._serialized_start=185
  _USERNAMES._serialized_end=226
  _LISTUSERNAMESPARAMS._serialized_start=228
  _LISTUSERNAMESPARAMS._serialized_end=267
  _SENDPARAMS._serialized_start=269
  _SENDPARAMS._serialized_end=346
  _CHATMESSAGE._serialized_start=348
  _CHATMESSAGE._serialized_end=430
  _PENDINGMESSAGESPAYLOAD._serialized_start=432
  _PENDINGMESSAGESPAYLOAD._serialized_end=483
  _RETURNSTATUSPAYLOAD._serialized_start=485
  _RETURNSTATUSPAYLOAD._serialized_end=591
  _ChatServer._serialized_start=594
  _ChatServer._serialized_end=1073
# @@protoc_insertion_point(module_scope)
